steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/gcp-beat-notification-artifact-repo/gcp-beat-notification-service-image:$COMMIT_SHA', '.']
  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/gcp-beat-notification-artifact-repo/gcp-beat-notification-service-image:$COMMIT_SHA']
images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/gcp-beat-notification-artifact-repo/gcp-beat-notification-service-image:$COMMIT_SHA'